# =========================================
# Frontend Web - Deployment & Service
# =========================================
# YOUR REACT APP RUNNING IN KUBERNETES!
#
# KEY CONCEPTS:
# 1. Nginx serving React static files
# 2. Nginx proxies API calls to backend-service:5000
# 3. NodePort service - accessible from your browser!
# 4. 2 replicas for high availability
#
# ACCESS:
# - From browser: http://localhost:30080
# - Or: kubectl port-forward service/frontend-service 3000:80
#
# CHANGE THIS: Update image tag to your actual SHA from Docker Hub!
# =========================================

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80        
    targetPort: 80   
    nodePort: 30080   

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: frontend
  
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  
  template:
    metadata:
      labels:
        app: frontend
    spec:
      
      containers:
      - name: frontend
        image: tomernos/connecthub-frontend:1b46d09
        
        imagePullPolicy: Always
        
        ports:
        - containerPort: 80
          name: http
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        
        # Health check - is Nginx serving files?
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
