{{- range $name, $config := .Values.deployments }}
{{- if $config.enabled }}
{{- $secretData := index $.Values.secrets $name }}
{{- if $secretData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ include "connecthub.namespace" $ }}
  labels:
    app: {{ $name }}
    {{- include "connecthub.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.secrets.dockerhub.enabled }}
# =========================================
# Docker Hub Registry Secret
# =========================================
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.global.dockerhubSecretName }}"
  namespace: {{ include "connecthub.namespace" . }}
  labels:
    {{- include "connecthub.labels" . | nindent 4 }}

# SPECIAL TYPE for Docker registry authentication
type: kubernetes.io/dockerconfigjson

data:
  .dockerconfigjson: {{ .Values.secrets.dockerhub.config | quote }}

{{- end }}
