{{- range $name, $config := .Values.secretProviderClasses }}
{{- if $config.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "connecthub.fullname" $ }}{{ $name }}
  namespace: {{ include "connecthub.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- include "connecthub.labels" $ | nindent 4 }}
spec:
  provider: {{ $config.provider | default "aws" }}
  parameters:
    {{- if eq $config.provider "aws" }}
    region: {{ $config.parameters.region | quote }}
    usePodIdentity: {{ $config.parameters.usePodIdentity | default "true" | quote }}
    objects: |
      {{- range $config.parameters.objects }}
      - objectName: {{ .objectName | quote }}
        objectType: {{ .objectType | default "secretsmanager" | quote }}
        {{- if .objectAlias }}
        objectAlias: {{ .objectAlias | quote }}
        {{- end }}
      {{- end }}
    {{- else if eq $config.provider "azure" }}
    usePodIdentity: {{ $config.parameters.usePodIdentity | default "true" | quote }}
    keyvaultName: {{ $config.parameters.keyvaultName | quote }}
    cloudName: {{ $config.parameters.cloudName | default "" | quote }}
    tenantId: {{ $config.parameters.tenantId | quote }}
    objects: |
      {{- range $config.parameters.objects }}
      - |
        objectName: {{ .objectName | quote }}
        objectType: {{ .objectType | default "secret" | quote }}
        {{- if .objectAlias }}
        objectAlias: {{ .objectAlias | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  
  {{- if $config.secretObjects }}
  # Create Kubernetes Secret from cloud provider secrets
  secretObjects:
  {{- range $config.secretObjects }}
  - secretName: {{ include "connecthub.fullname" $ }}{{ .secretName }}
    type: {{ .type | default "Opaque" }}
    data:
    {{- range .data }}
    - objectName: {{ .objectName | quote }}
      key: {{ .key | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
