{{- range $name, $config := .Values.serviceAccounts }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connecthub.fullname" $ }}{{ $name }}
  namespace: {{ include "connecthub.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
    {{- include "connecthub.labels" $ | nindent 4 }}
  {{- if $config.annotations }}
  annotations:
    {{- range $key, $value := $config.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
