{{- if .Values.secretProviderClasses }}
{{- range $name, $config := .Values.secretProviderClasses }}
{{- if $config.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "connecthub.labels" $ | nindent 4 }}
spec:
  provider: {{ $config.provider | default "aws" }}
  parameters:
    {{- if eq $config.provider "aws" }}
    region: {{ $config.parameters.region | quote }}
    usePodIdentity: {{ $config.parameters.usePodIdentity | default "true" | quote }}
    objects: |
      {{- range $config.parameters.objects }}
      - objectName: {{ .objectName | quote }}
        objectType: {{ .objectType | default "secretsmanager" | quote }}
        {{- if .objectAlias }}
        objectAlias: {{ .objectAlias | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  
  {{- if $config.secretObjects }}
  secretObjects:
  {{- range $config.secretObjects }}
  - secretName: {{ .secretName }}
    type: {{ .type | default "Opaque" }}
    data:
    {{- range .data }}
    - objectName: {{ .objectName | quote }}
      key: {{ .key | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
