{{- if .Values.serviceAccounts }}
{{- range $name, $config := .Values.serviceAccounts }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "connecthub.labels" $ | nindent 4 }}
  {{- if $config.annotations }}
  annotations:
    {{- range $key, $value := $config.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
