apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: chatapp
    environment: staging
spec:
  project: chatapp
  
  source:
    repoURL: https://github.com/tomernos/CompanyGitOps.git
    targetRevision: main
    path: applications/chatapp/helm-chart
    
    # Helm configuration
    helm:
      releaseName: chatapp
      valueFiles:
        - ../staging/values.yaml  # Staging-specific values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: chatapp-staging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

